sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sohaib629/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true sohaib629/docker-react2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-687963397861"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: AKIA2ALOQL3S6YZ7TY5M
  secret_access_key:
    secure: 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
