sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sohaib629/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true sohaib629/docker-react2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-687963397861"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
